name: Build and Push

on:
  push:
    branches: ["main"]


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set Repo Variable
        id: set-repo
        run: |
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          REPO_NAME="${REPO_NAME//_/-}"
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_OUTPUT
      -
        name: Grab Commit Hash
        id: commit-hash
        run: |
          github_sha_hash=${{ github.sha }}
          github_sha_short="${github_sha_hash:0:7}"

          echo "GitHub commit hash: ${github_sha_short}"
          echo "COMMIT_HASH=${github_sha_short}" >> $GITHUB_OUTPUT
      -
        name: Create build commit
        run: |
          github_sha_hash=${{ github.sha }}
          github_sha_short="${github_sha_hash:0:7}"

          echo "GitHub commit hash: ${github_sha_short}"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/${{ steps.set-repo.outputs.REPO_NAME }}:${{ steps.commit-hash.outputs.COMMIT_HASH }}
      
      - name: Save Latest Build Tag as a GitHub Org Secret
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          REPO_NAME="${REPO_NAME//-/_}"
          REPO_NAME=${REPO_NAME^^}

          BUILD=${{ secrets.DOCKERHUB_USERNAME}}/${{ steps.set-repo.outputs.REPO_NAME }}:${{ steps.commit-hash.outputs.COMMIT_HASH }}

          echo "[INFO] Setting the GitHub Org secret to the latest Helm Chart package: $BUILD"
          gh secret set ${REPO_NAME}_DOCKER_BUILD --org Plant-Coach --visibility all --body "$BUILD"
          
          echo "[INFO] Done!"