on:
  push:
  # workflow_run:
  #   workflows:
  #     - "Build and Push"
  #     - "Test and Lint"
  #   branches:
  #     - main
  #   types:
  #     - completed

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: ruby
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
      - name: Print output for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo "${{ steps.release.outputs }}"